### ISSUE TITLE
Syntax Error: Unexpected token '?'

### ISSUE THREAD

**Issue by CyberTrainer23** [richawo/minimal-llm-ui#10]
On a fresh install I'm getting the following error
![image](https://github.com/richawo/minimal-llm-ui/assets/150097337/fcbd0b0e-5617-4ce6-8c99-0f8763d7c37f)

**Comment by MostlyKIGuess** [comment]
This is an error because your node version is lower than 14.0.1, can you tell me what is your node version?

use 
```
node -v
```
in your terminal  to get the version

basically this app requires you to have a node v >= 14.0.1
@richawo 

should I add this into documentation?

**Comment by richawo** [comment]
Solved in #13 , thanks
