### ISSUE TITLE
Text overwritten

### ISSUE THREAD

**Issue by kavap** [richawo/minimal-llm-ui#15]
### Details

![overwrittentext](https://github.com/richawo/minimal-llm-ui/assets/6875959/71f8470b-b04e-49c4-aa99-664769c54b45)

<details open>
<summary>Checklist</summary>

- [X] Modify `src/app/page.tsx` ✓ https://github.com/richawo/minimal-llm-ui/commit/464c4ef69e22311016ba74bd59e046f240fa8572
- [X] Running GitHub Actions for `src/app/page.tsx` ✓
- [X] Create `src/app/some_style_file.css` ✓ https://github.com/richawo/minimal-llm-ui/commit/bf33df4d708cc46f0ac0f097b6c9a7da20c72d66
- [X] Running GitHub Actions for `src/app/some_style_file.css` ✓

![Flowchart](https://raw.githubusercontent.com/richawo/minimal-llm-ui/sweep/assets/ce48e5bd3767b13a82d6e2a998160039f9cc5915dd7db3a2f826bfcad6c7f829_15_flowchart.svg)
</details>

**Comment by wwzeng1** [comment]
Sweep: the text can overlap linewise in the assistant message. Please fix this.

**Comment by wwzeng1** [comment]
@richawo Please check this out! Let me know if it doesn't work :)

**Comment by richawo** [comment]
@wwzeng1 @kavap thanks for flagging, will check it tonight!
