### ISSUE TITLE
[Question] How does it handle switching LLMs mid-convo?

### ISSUE THREAD

**Issue by taoeffect** [richawo/minimal-llm-ui#17]
Very cool project! 😄 

I'm wondering, how does switching LLMs mid-convo work? Is this something handled by `langchain`? I skimmed the codebase and couldn't figure it out.

**Comment by richawo** [comment]
@taoeffect thanks!

The message history is handled using `langchain` and the model can be switched at any point. So you can begin with llama-2 for example and then switch to zephyr thereafter. The same history is used regardless of the chosen model however the model used to interpret the context + create the response is based on your active model.

**Comment by taoeffect** [comment]
Cool thanks for the answer @richawo! I wonder what langchain does under the hood, if you happen to know I'd be curious to know! For example, does "switching" and sending a followup question just mean that it sends the entire history of the chat as-is to the new LLM, plus your new question?

**Comment by richawo** [comment]
Bingo @taoeffect!

Not fully sure what Langchain are doing under the hood but whatever it's doing is getting it into a format Ollama can easily consume regardless of the underlying model. Switching between models may not always yield perfect results, but it seems fine so far.
