### ISSUE TITLE
ability to define end-point URLs

### ISSUE THREAD

**Issue by chymian** [richawo/minimal-llm-ui#2]
I wanted to do a testride but its not connecting to docker-run ollama. (see below)
which could maybe worked around, if we could  define the endpoints for the ollama-server (might run on another machine) 
and the own IP:PORT to bind to.

any plans for that?

and how to use it with docker?

```log
  62 | 
  63 | function getInitialModel() {
> 64 |   fetch("http://localhost:11434/api/tags")
     |  ^
  65 |     .then((response) => response.json())
  66 |     .then((data) => {
  67 |       console.log(data);
```

**Comment by richawo** [comment]
This is a good point, wasn't an immediate plan but definitely something worth considering, because I don't think it's a massive change!

**Comment by rob-mosher** [comment]
I've got an implementation working and am putting together a PR.

**Comment by rob-mosher** [comment]
Following up, I've added this feature under PR #22.

**Comment by richawo** [comment]
merged!
