### ISSUE TITLE
installation problems

### ISSUE THREAD

**Issue by JohnOstrowick** [richawo/minimal-llm-ui#20]
Hi. After cloning the repo and attempting to update node (not your problem I know), I can get to at most node 12.22.9

this is latest ubuntu

Then when I try run npm run dev

john@john-GF63-Thin-11SC:~/ai/minimal-llm-ui$ npm run dev

> minimal-llm-ui@0.1.0 dev
> next dev

sh: 1: next: not found

**Comment by adithya3403** [comment]
run `npm install`
then `npm run dev`
should work

**Comment by richawo** [comment]
Not a repo issue
